"""
src/api/app.py

Ponto de entrada da aplicação FastAPI.
Monta os routers, regista os error handlers globais,
configura o Swagger UI e o CORS.
"""
from __future__ import annotations

import logging
import time
from contextlib import asynccontextmanager

from fastapi import FastAPI, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from src.gateway.config import get_settings

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Lifespan — startup / shutdown
# ─────────────────────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    settings = get_settings()
    from src.gateway.key_store import init_key_store
    key_store = init_key_store(settings.database_url)
    await key_store.startup()
    logger.info(
        "FactorRouter starting | upstream=%s | port=%s | %d keys loaded",
        settings.upstream_url,
        settings.port,
        key_store.cache_size,
    )
    yield
    await key_store.shutdown()
    logger.info("FactorRouter shutting down.")


# ─────────────────────────────────────────────────────────────────────────────
# App
# ─────────────────────────────────────────────────────────────────────────────

settings = get_settings()

app = FastAPI(
    title="FactorRouter",
    description="""
## What is this?

Drop-in replacement for the OpenAI SDK with automatic model routing and a
centralized cost center.

Your apps call this gateway instead of OpenRouter/OpenAI directly.
The gateway picks the model, proxies the stream, and records cost.

## Authentication

All endpoints require `Authorization: Bearer <key>`.
Get your API key from the gateway administrator.

## Required headers

All requests to `/v1/*` must include:

| Header | Type | Description |
|---|---|---|
| `X-App-Id` | string | App identifier (e.g. `severino-wa`) |
| `X-Turn-Id` | UUID v4 | Generated by the agent at the start of each turn |
| `X-Session-Id` | string | Chat session ID |
| `X-Conversation-Id` | string or `"null"` | Conversation ID, if any |
| `X-User-Message` | string | First 300 characters of the user message |
| `X-User-Id` | string or `"null"` | User ID |
| `X-User-Name` | string or `"null"` | User name |
| `X-User-Email` | string or `"null"` | User email |
| `X-Company-Id` | string or `"null"` | Company ID |
| `X-Company-Name` | string or `"null"` | Company name |

> **Note:** Missing header = `400`. Unknown value = send the string `"null"`.
    """,
    version="2.0.0",
    lifespan=lifespan,
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_tags=[
        {
            "name": "proxy",
            "description": "Main endpoint — OpenAI SDK compatible.",
        },
        {
            "name": "usage",
            "description": "Cost center — logs and statistics.",
        },
        {
            "name": "system",
            "description": "Health check and system information.",
        },
        {
            "name": "admin",
            "description": "App and API key management (X-Admin-Secret).",
        },
    ],
)


# ─────────────────────────────────────────────────────────────────────────────
# CORS
# ─────────────────────────────────────────────────────────────────────────────

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],       # ajustar em produção
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─────────────────────────────────────────────────────────────────────────────
# Middleware — request timing
# ─────────────────────────────────────────────────────────────────────────────

@app.middleware("http")
async def add_timing_header(request: Request, call_next):
    start = time.perf_counter()
    response = await call_next(request)
    elapsed = time.perf_counter() - start
    response.headers["X-Response-Time-Ms"] = str(round(elapsed * 1000, 2))
    return response


# ─────────────────────────────────────────────────────────────────────────────
# Error handlers globais — erros claros e estruturados
# ─────────────────────────────────────────────────────────────────────────────

@app.exception_handler(404)
async def not_found_handler(request: Request, exc):
    return JSONResponse(
        status_code=status.HTTP_404_NOT_FOUND,
        content={
            "error": "not_found",
            "message": f"Endpoint '{request.method} {request.url.path}' does not exist.",
            "docs": "/docs",
        },
    )


@app.exception_handler(405)
async def method_not_allowed_handler(request: Request, exc):
    return JSONResponse(
        status_code=status.HTTP_405_METHOD_NOT_ALLOWED,
        content={
            "error": "method_not_allowed",
            "message": f"Method '{request.method}' is not allowed for this endpoint.",
        },
    )


@app.exception_handler(500)
async def internal_error_handler(request: Request, exc):
    logger.exception("Unhandled internal error: %s %s", request.method, request.url.path)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={
            "error": "internal_server_error",
            "message": "Internal gateway error. Check the logs.",
        },
    )


# ─────────────────────────────────────────────────────────────────────────────
# Routers
# ─────────────────────────────────────────────────────────────────────────────

from src.api.routes import health, proxy, usage, admin   # noqa: E402

app.include_router(health.router)
app.include_router(proxy.router, prefix="/v1", tags=["proxy"])
app.include_router(usage.router, prefix="/usage", tags=["usage"])
app.include_router(admin.router, prefix="/admin", tags=["admin"])